#!/bin/bash

# Auto-Build Environment Setup
# Feature: Feed Image Proxy with Hotlink Protection Bypass
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Feature: Feed Image Proxy"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PREREQUISITE CHECKS
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js: $(node --version)${NC}"

# Check PHP
if ! command -v php &> /dev/null; then
    echo -e "${YELLOW}PHP is not installed - API endpoints won't work${NC}"
else
    echo -e "${GREEN}PHP: $(php --version | head -1)${NC}"
fi

# Check npm dependencies
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# ============================================
# CREATE CACHE DIRECTORY
# ============================================

echo ""
echo "Setting up cache directory..."

mkdir -p api/cache/images
if [ ! -f "api/cache/images/.gitkeep" ]; then
    touch api/cache/images/.gitkeep
    echo -e "${GREEN}Created api/cache/images/.gitkeep${NC}"
else
    echo -e "${GREEN}Cache directory already exists${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting development server..."

# Start Vite dev server (handles both frontend and API proxy)
npm run dev &
DEV_PID=$!

wait_for_service 3000 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:     http://localhost:3000"
echo "  API:          http://localhost:3000/api"
echo ""
echo "Image Proxy:    http://localhost:3000/api/feeds/image-proxy.php"
echo ""
echo "To stop the dev server: kill $DEV_PID"
echo ""
echo "Key Commands:"
echo "  npm test              - Run tests"
echo "  npm run test:run      - Run tests once"
echo "  npx tsc --noEmit      - Type check"
echo ""
