export { WidgetWrapper } from './WidgetWrapper'
export { NewsWidget } from './news/NewsWidget'
export { WeatherWidget } from './weather/WeatherWidget'
export { CalendarWidget } from './calendar/CalendarWidget'
export { StockWidget } from './stocks/StockWidget'
export { LotteryWidget } from './lottery/LotteryWidget'
export { DailyWidget } from './daily/DailyWidget'
export { HistoryWidget } from './history/HistoryWidget'
