#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 002 - Calendar Timezone Handling

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Calendar Timezone Handling"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/benjaminrogers/VSCode/BennernetLLC/agents/portal"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found. Please install npm first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm --version)${NC}"

# Check PHP (for backend)
if ! command -v php &> /dev/null; then
    echo -e "${YELLOW}⚠ PHP not found. Backend changes cannot be verified.${NC}"
else
    echo -e "${GREEN}✓ PHP $(php --version | head -1)${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
cd "$PROJECT_ROOT"

if [ ! -d "node_modules" ]; then
    npm install
else
    echo -e "${GREEN}✓ Dependencies already installed${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting development server..."

# Start Vite dev server in background
npm run dev &
VITE_PID=$!

# Wait for frontend
wait_for_service 3000 "Frontend (Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Development Commands:"
echo "  npm run dev       - Start dev server"
echo "  npm run test      - Run tests in watch mode"
echo "  npm run test:run  - Run tests once"
echo "  npm run build     - Build for production"
echo ""
echo "PHP Verification:"
echo "  php -l api/feeds/calendar.php  - Check PHP syntax"
echo ""
echo "Press Ctrl+C to stop the dev server"
echo ""

# Keep script running
wait $VITE_PID
